[package]
name = "lmt"
version = "0.11.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/NitrogenLinux/elements"
license = "LICENSE"
authors = ["tekq", "Nitrogen Project"]

[dependencies]
nix = "0.24.2"
words-count = "0.1.3"
