[package]
name = "vmod"
version = "0.14.0"
edition = "2021"

[dependencies]
tar = "0.4.38"
xz2 = "0.1.0"
sqlite = "0.30.3"
version-compare = "0.1.0"
rand = "0.8.4"
base64 = "0.21.0"
tempdir = "0.3.7"
words-count = "0.1.3"
colour = "0.7.0"
